# Basic dependabot.yml file with

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for Ruby/Bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
